window.translations_hash = 'b7925b46';
// XREF:LANGUAGE_TRANSLATIONS_LIST ← search for this in our codebase for all places to update.
// These are the languages that are supported in our portal.
define({
	root: true,
	el: true,
	en: true,
	'en-tvrepublic': true,
	'en-vermantia': true,
	'en-yodeck': true,
	es: true,
	fi: true,
	fr: true,
	'fr-CA': true,
	'fr-pyramide': true,
	it: true,
	ms: true,
	nb: true,
	nl: true,
	sl: true,
	tr: true,
	'tr-bulutekran': true,
	pt: true,
	sv: true,
	de: true,
	vi: true,
	ru: true,
	ja: true,
	'pt-BR': true,
	zz: true,
	uk: true,
	da: true,
	hu: true,
	ka: true,
	pl: true,
});
